#!/bin/sh
#
# Insert selected git-ticket issue identifier in the comment.
# if no selected issue, print in comments the list of open issues.
#

if [ "$2" = "commit" -o "$2" = "merge" ]
then
    exit 0
fi

cmtChar=`git config --get core.commentchar`
hashChar="#"
if [ "$cmtChar" = "" ]
then
	cmtChar="#"
fi
if [ "$cmtChar" = "#" ]
then
	hashChar=":"
fi

ISSUE=`git ticket show --field shortId`
if [ "$ISSUE" = "" ]
then
  echo "No ticket selected. use \"git ticket select\" to choose your active ticket before committing."
  exit 1
else
	sed -i "1i$hashChar$ISSUE " "$1"
fi
